"""all fields are requires

Revision ID: 33826f55368f
Revises: 214cf078815a
Create Date: 2025-05-14 15:47:10.683609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33826f55368f'
down_revision: Union[str, None] = '214cf078815a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'skills',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'course',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'qualification',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'qualification',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'course',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'skills',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
